development:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: ENV['GMAIL_USER']
  :password: ENV['GMAIL_PASS']
  :enable_starttls_auto: true
production:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: ENV['GMAIL_USER']
  :password: ENV['GMAIL_PASS']
  :enable_starttls_auto: true
